print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Master/20w-ensemble/ensemble-vr-seat/Assets/goodSeat.mb"`)
{		
	file -o "/Users/Master/20w-ensemble/ensemble-vr-seat/Assets/goodSeat.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Master/20w-ensemble/ensemble-vr-seat/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/Master/20w-ensemble/ensemble-vr-seat/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/Master/20w-ensemble/ensemble-vr-seat/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
